### ISSUE TITLE
My wishlist

### ISSUE THREAD

**Issue by PiotrPrzetacki** [MikiP98/MultiScaler-Plus#6] opened 2024-08-10 12:03 UTC
- [ ] update run_webui.bat to work

- [x] .gitignore \_\_pycache\_\_ dirs
- [x]  add buildtools installer (with this flags): `vs_buildtools.exe --norestart --passive --downloadThenInstall --includeRecommended --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Workload.MSBuildTools`

- [x] no module found: `pip install pillow-jxl-plugin`

- [x]  add to installer to enable running ps scripts: `Set-ExecutionPolicy unrestricted -Scope Process`
- [x] run_console.bat python: can't open file 'C:\\Users\\WDAGUtilityAccount\\Desktop\\MultiScaler-Plus\\src\\standalone.py': [Errno 2] No such file or directory

**Comment by MikiP98** [comment] 2024-08-10 12:20
Fixed `run_console.bat`, (renamed to `run_console.ps1`) in commit [8dd220e](https://github.com/MikiP98/MultiScaler-Plus/commit/8dd220e72aa12f88e9f7a94d6c686a3e29f190da)

**Comment by MikiP98** [comment] 2024-08-10 12:48
@PiotrPrzetacki Both `.gitignore` and `src/.gitignore` have `__pycache__` added to ignore.  

While running command `git rm --cached src/__pycache__` I get an error: `fatal: pathspec 'src/__pycache__' did not match any files`.  
Running command `git add src/__pycache__` results in a waring:
```
The following paths are ignored by one of your .gitignore files:
src/__pycache__
hint: Use -f if you really want to add them.
hint: Disable this message with "git config advice.addIgnoredFile false"
```  

I also don't have `__pycache__` dir in the main folder.
I see that one is located in all subfolder/packages, but running `git rm` on them produces the same error

**Comment by MikiP98** [comment] 2024-08-10 12:53
As WebUI is currently under rewrite and the server side code is broken due to refactor I decided to remove the `run_webui.bat` and most files related to the old WebUI

**Comment by MikiP98** [comment] 2024-08-10 13:03
@PiotrPrzetacki I can't reproduce:
> no module found: `pip install pillow-jxl-plugin`

My logs:
```
C:\Users\...>pip install pillow-jxl-plugin
Defaulting to user installation because normal site-packages is not writeable
Collecting pillow-jxl-plugin
  Downloading pillow_jxl_plugin-1.2.6-cp312-none-win_amd64.whl.metadata (2.9 kB)
Requirement already satisfied: packaging in c:\users\...\appdata\roaming\python\python312\site-packages (from pillow-jxl-plugin) (24.1)
Requirement already satisfied: pillow in c:\program files\python312\lib\site-packages (from pillow-jxl-plugin) (10.2.0)
Downloading pillow_jxl_plugin-1.2.6-cp312-none-win_amd64.whl (4.1 MB)
   ---------------------------------------- 4.1/4.1 MB 3.0 MB/s eta 0:00:00
Installing collected packages: pillow-jxl-plugin
Successfully installed pillow-jxl-plugin-1.2.6
```

How did you fix it after the encounter?
Did you use Python 3.12?

**Comment by PiotrPrzetacki** [comment] 2024-08-10 13:45
It was module not found error: pillow-jxl. Once I had this error, once I didn't. Most likely because I stopped the installation after another error and resumed it later.

I think it's safe to assume it works fine.

**Comment by MikiP98** [comment] 2024-08-10 13:46
I've added the line `Set-ExecutionPolicy unrestricted -Scope Process` at the beginning of the power shell script in hope of it working in commit [8164d3d](https://github.com/MikiP98/MultiScaler-Plus/commit/8164d3d51746f0c6f4fa6ddb9e2e800d78be255b)

**Comment by MikiP98** [comment] 2024-08-10 13:49
@PiotrPrzetacki Do you propose adding the `vs_buildtools.exe` to my project files or making a script that downloads and later runs it just as in the `ImDisc` install script?
Also why do you think flag `--downloadThenInstall` should be present?

**Comment by PiotrPrzetacki** [comment] 2024-08-10 14:26
I would do the same as with ImDisc.
idk if this flag is necessary I found this command on stackoverflow. Installing buildtools without some of those flags (I don't know which flag is important) is not enough.

**Comment by MikiP98** [comment] 2024-08-10 19:00
I've added vs_buildtools.exe install script in commit [622c492](https://github.com/MikiP98/MultiScaler-Plus/commit/622c492b8c233c8a12bad25cd4381e4c70efba69)

**Comment by MikiP98** [comment] 2024-08-10 19:01
@PiotrPrzetacki Could you double check everything and close the issue?
Or do you want to close it only after the WebUI be added back?
Also could you elaborate on the `__pychache__`: https://github.com/MikiP98/MultiScaler-Plus/issues/6#issuecomment-2281568360

**Comment by PiotrPrzetacki** [comment] 2024-08-16 10:33
@MikiP98 

__pycache__ is already ignored by git, my bad

This still doesn't work:
>add to installer to enable running ps scripts: Set-ExecutionPolicy unrestricted -Scope Process

because you have to set execution policy **_before_** running ps script. See [this](https://stackoverflow.com/questions/42897554/powershell-executionpolicy-change-bypass) (option 3) and try to add `-executionpolicy bypass` flag like:
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -executionpolicy bypass .\install_vs_buildtools.ps1
```

And do the same for Imdisk installer

**Comment by MikiP98** [comment] 2024-08-21 19:13
@PiotrPrzetacki Installation scripts should be fixed now :)

**Comment by PiotrPrzetacki** [comment] 2024-08-22 11:20
yes, installer works now

**Closed as completed** 2024-09-12 17:12 UTC
Labels: bug, enhancement
